openapi: 3.0.2
info:
  title: berlinplaces
  version: 0.0.1
  description: autocomplete and geocode berlin places (see [example](/web))
tags:
  - name: api
paths:

  /api:
    get:
      tags:
        - api
      summary: get completions
      description: get completions
      parameters:
        - in: query
          name: text
          schema:
            type: string
          description: the text to look up
          example:
            Brandenburger Tor
      responses:
        '200':
          description: OK (success)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/placesResult'
              example:
                - distance: 5
                  percentage: 0
                  place:
                    placeID: '507317'
                    parentPlaceID: '465333'
                    osmID: ''
                    class: highway
                    type: residential
                    name: Brandenburger Straße
                    street: ''
                    houseNumber: ''
                    suburb: ''
                    postcode: '13405'
                    city: ''
                    lat: '52.5558099'
                    lon: '13.3138105'
        '500':
          description: InternalServerError
# components
components:
  schemas:
    placesResult:
      type: object
      properties:
        distance:
          type: integer
        percentage:
          type: integer
        place:
          $ref: '#/components/schemas/place'
    place:
      type: object
      properties:
        placeID:
          type: integer
        parentPlaceID:
          type: integer
        osmID:
          type: string
        class:
          type: string
        type:
          type: string
        name:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        suburb:
          type: string
        postcode:
          type: string
        city:
          type: string
        lat:
          type: string
        lon:
          type: string
