openapi: 3.0.2
info:
  title: berlinplaces
  version: 0.0.1
  description: autocomplete and geocode berlin places (see [example](/web))
tags:
  - name: api
paths:

  /api:
    get:
      tags:
        - api
      summary: get completions
      description: get completions
      parameters:
        - in: query
          name: text
          schema:
            type: string
          description: the text to look up
          example:
            elisabethfellerweg
      responses:
        '200':
          description: OK (success)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/placesResult'
              example:
                - distance: 0
                  percentage: 0
                  place:
                    placeID: 541950
                    parentPlaceID: 465999
                    class: highway
                    type: living_street
                    name: Elisabeth-Feller-Weg
                    boundary: Lichterfelde
                    neighbourhood: Schweizer Viertel
                    postcode: '12205'
                    city: Berlin
                    lat: 52.4280125
                    lon: 13.2992439
                    relevance: 1
                    simpleName: elisabethfellerweg
                - distance: 6
                  percentage: 0
                  place:
                    placeID: 526802
                    parentPlaceID: 729970
                    class: highway
                    type: residential
                    name: Elisabethweg
                    boundary: Pankow
                    postcode: '13187'
                    city: Berlin
                    lat: 52.5741318
                    lon: 13.4058554
                    relevance: 0
                    simpleName: elisabethweg

        '500':
          description: InternalServerError
# components
components:
  schemas:
    placesResult:
      type: object
      properties:
        distance:
          type: integer
        percentage:
          type: integer
        place:
          $ref: '#/components/schemas/place'
    place:
      type: object
      required:
        - placeID
        - parentPlaceID
        - class
        - type
        - name
        - postcode
        - city
        - lat
        - lon
        - relevance
        - simpleName
      properties:
        placeID:
          type: number
          format: int64
        parentPlaceID:
          type: number
          format: int64
        osmID:
          type: string
        class:
          type: string
        type:
          type: string
        name:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        suburb:
          type: string
        postcode:
          type: string
        city:
          type: string
        lat:
          type: number
          format: float64
        lon:
          type: number
          format: float64
        relevance:
          type: number
        simpleName:
          type: string