openapi: 3.0.2
info:
  title: berlinplaces
  version: 0.0.1
  description: autocomplete and geocode berlin places (see [example](/web))
tags:
  - name: api
paths:

  /api:
    get:
      tags:
        - api
      summary: get completions
      description: get completions
      parameters:
        - in: query
          name: text
          schema:
            type: string
          description: the text to look up
          example:
            Brandenburger Tor
      responses:
        '200':
          description: OK (success)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/placesResult'
              example:
                - distance: 5
                  percentage: 0
                  place:
                    PlaceID: '507317'
                    ParentPlaceID: '465333'
                    OSMID: ''
                    Class: highway
                    Type: residential
                    Name: Brandenburger Straße
                    Street: ''
                    HouseNumber: ''
                    Suburb: ''
                    Postcode: '13405'
                    City: ''
                    Lat: '52.5558099'
                    Lon: '13.3138105'
                - distance: 6
                  percentage: 0
                  place:
                    PlaceID: '533869'
                    ParentPlaceID: '729551'
                    OSMID: ''
                    Class: highway
                    Type: footway
                    Name: Brandenburgplatz
                    Street: ''
                    HouseNumber: ''
                    Suburb: ''
                    Postcode: '12555'
                    City: ''
                    Lat: '52.4552786'
                    Lon: '13.5919091'
        '500':
          description: InternalServerError
# components
components:
  schemas:
    placesResult:
      type: object
      properties:
        distance:
          type: integer
        percentage:
          type: integer
        place:
          $ref: '#/components/schemas/place'
    place:
      type: object
      properties:
        PlaceID:
          type: integer
        ParentPlaceID:
          type: integer
        OSMID:
          type: string
        Class:
          type: string
        Type:
          type: string
        Name:
          type: string
        Street:
          type: string
        HouseNumber:
          type: string
        Suburb:
          type: string
        Postcode:
          type: string
        City:
          type: string
        Lat:
          type: string
        Lon:
          type: string
